### PR TITLE
numba-cuda 0.0.21

### PR DESCRIPTION
**Pull request by cbouss**
numba-cuda 0.0.21

**Destination channel:** main

### Links

- PKG-6007
- https://github.com/NVIDIA/numba-cuda/tree/v0.0.21

### CODE REVIEW

**Review by danpetry — COMMENTED** [review]
This I guess assumes that cuda is installed on the system rather than using our conda packages. Is that ok?

**Review by Jrice1317 — APPROVED** [review]
LGTM, but I'm curious about the tests as well as the `recipe.yaml`. Is that something we plan to adopt soon?

**Comment by cbouss** [comment]
> LGTM, but I'm curious about the tests as well as the `recipe.yaml`. Is that something we plan to adopt soon?

recipe.yaml is the new format of conda recipes. Which we won't be adopting soon. You'll see more feedstock from conda-forge using it though.

**Comment by cbouss** [comment]
> * https://github.com/NVIDIA/numba-cuda/tree/v0.0.21

This is through numba, as I understand: https://nvidia.github.io/numba-cuda/user/overview.html#software

**Comment by danpetry** [comment]
Those instructions tell you to install cuda conda packages - so should we provide them via this recipe instead?
If we do that, some tests, to test the integration, would I think be useful

**Comment by cbouss** [comment]
I think it's best to follow the conda-forge recipe in this case. As the conda-forge recipe is maintained by one of the maintainers of numba-cuda.

**Comment by danpetry** [comment]
i see, ok

**Review by danpetry — APPROVED** [review]

**Pull request merged**
